cursor            #ffb595
cursor_text_color #542106

foreground            #f1dfd8
background            #140c09
selection_foreground  #442a1f
selection_background  #e6bead
url_color             #e6bead

#: black 000000 767676
color0  #1a110e
color8  #3d322e
#: red cc0403 f2201f
color1  #000000
color9  #8a380f
#: green 19cb00 23fd00
color2  #e6bead
color10 #ffdbcd
#: yellow cecb00 fffd00
color3  #d2c78f
color11 #efe3a9
#: blue 0d73cc 1a8fff
color4  #71361a
color12 #ffb595
#: magenta cb1ed1 fd28ff
color5  #5d4034
color13 #e6bead
#: cyan 0dcdcd 14ffff
color6  #4e471b
color14 #d2c78f
#: white dddddd ffffff
color7  #d8c2ba
color15 #f1dfd8

mark1_foreground #360f00
mark1_background #ffdbcd
mark2_foreground #2c160c
mark2_background #ffdbcd
mark3_foreground #201c00
mark3_background #efe3a9

active_tab_foreground #542106
active_tab_background #ffb595
inactive_tab_foreground #ffdbcd
inactive_tab_background #71361a

active_border_color #ffb595
inactive_border_color #542106
# bell_border_color #ff5a00
