cursor            #a3c9fe
cursor_text_color #00315b

foreground            #e1e2e8
background            #0c0e13
selection_foreground  #263141
selection_background  #bcc7db
url_color             #bcc7db

#: black 000000 767676
color0  #111418
color8  #32353a
#: red cc0403 f2201f
color1  #1d2633
color9  #566f93
#: green 19cb00 23fd00
color2  #bcc7db
color10 #d7e3f8
#: yellow cecb00 fffd00
color3  #d8bde3
color11 #f5d9ff
#: blue 0d73cc 1a8fff
color4  #1e4876
color12 #a3c9fe
#: magenta cb1ed1 fd28ff
color5  #3c4758
color13 #bcc7db
#: cyan 0dcdcd 14ffff
color6  #543f5e
color14 #d8bde3
#: white dddddd ffffff
color7  #c3c6cf
color15 #e1e2e8

mark1_foreground #001c38
mark1_background #d3e4ff
mark2_foreground #111c2b
mark2_background #d7e3f8
mark3_foreground #261431
mark3_background #f5d9ff

active_tab_foreground #00315b
active_tab_background #a3c9fe
inactive_tab_foreground #d3e4ff
inactive_tab_background #1e4876

active_border_color #a3c9fe
inactive_border_color #00315b
# bell_border_color #ff5a00
